#!/usr/bin/env python3
from __future__ import annotations

import argparse
import csv
import json
from datetime import datetime
from pathlib import Path
from typing import List, Dict, Any


TIME_FORMATS = [
    "%Y/%m/%d %H:%M:%S.%f",
    "%Y/%m/%d %H:%M:%S",
]


def parse_timestamp(ts: str) -> datetime:
    ts = ts.strip()
    for fmt in TIME_FORMATS:
        try:
            return datetime.strptime(ts, fmt)
        except ValueError:
            continue
    raise ValueError(f"Unsupported timestamp format: {ts}")


def maybe_float(x: str) -> float:
    x = x.strip()
    if x.endswith(" W"):
        x = x[:-2].strip()
    return float(x)


def load_power_trace(path: Path) -> List[Dict[str, Any]]:
    rows = []
    with path.open("r", encoding="utf-8", newline="") as f:
        reader = csv.DictReader(f)
        for row in reader:
            rows.append(row)
    if not rows:
        raise RuntimeError(f"No telemetry rows found in: {path}")
    return rows


def integrate_energy_joules(rows: List[Dict[str, Any]]) -> Dict[str, Any]:
    # Use trapezoidal-ish midpoint average between consecutive samples
    parsed = []
    for r in rows:
        ts = parse_timestamp(r["timestamp"])
        p = maybe_float(r["power.draw"])
        parsed.append((ts, p))

    total_j = 0.0
    total_s = 0.0

    for i in range(len(parsed) - 1):
        t0, p0 = parsed[i]
        t1, p1 = parsed[i + 1]
        dt = (t1 - t0).total_seconds()
        if dt <= 0:
            continue
        p_avg = 0.5 * (p0 + p1)
        total_j += p_avg * dt
        total_s += dt

    mean_power_w = (total_j / total_s) if total_s > 0 else 0.0

    return {
        "samples": len(rows),
        "duration_s": total_s,
        "energy_j": total_j,
        "mean_power_w": mean_power_w,
    }


def main():
    parser = argparse.ArgumentParser(
        description="Estimate energy from a power trace CSV generated by nvidia-smi."
    )
    parser.add_argument("--trace-csv", required=True, help="Input power trace CSV")
    parser.add_argument("--out-json", required=True, help="Output JSON path")
    args = parser.parse_args()

    trace_path = Path(args.trace_csv)
    out_path = Path(args.out_json)

    rows = load_power_trace(trace_path)
    stats = integrate_energy_joules(rows)

    out_path.parent.mkdir(parents=True, exist_ok=True)
    with out_path.open("w", encoding="utf-8") as f:
        json.dump(stats, f, indent=2)

    print(f"[nvml_energy] Wrote JSON: {out_path}")
    print(json.dumps(stats, indent=2))


if __name__ == "__main__":
    main()